<?xml version="1.0"?>
<robot>
  
  <!-- standoffs -->
  <macro name="standoffs" params="name parent length *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <visual>
        <origin xyz="${length/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${length} 0.035 0.025"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="${length/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${length} 0.035 0.025"/>
        </geometry>
      </collision>
    </link>
  </macro>

  <!-- cosmetics -->
  <macro name="arm_mount" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57 3.14 0" />
        <geometry>
          <mesh filename="package://maxwell_defs/meshes/arm_mount_28.stl" scale="1 1 1"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="0.02525 ${-0.003175/2} 0" rpy="0 0 0" />
        <geometry>
          <box size="0.0760 0.003175 0.038"/>
        </geometry>
      </collision>
    </link>
  </macro>

  <!-- the actual arm -->
  <macro name="max_lite_arm" params="name parent *origin">

    <!-- Arm Link -->
    <joint name="${name}_base_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link"/>
    <arm_mount name="${name}_left_mount" parent="${name}_link">
      <origin xyz="-0.0513 0.0254 0" rpy="0 0 0"/>
    </arm_mount>
    <arm_mount name="${name}_right_mount" parent="${name}_link">
      <origin xyz="-0.0513 ${-0.0254+0.0047625} 0" rpy="0 0 0"/>
    </arm_mount>

    <!-- Shoulder pan -->
    <dynamixel_rx28_pan parent="${name}_link" name="${name}_shoulder_pan_servo" color="Black">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </dynamixel_rx28_pan>
    <rx28_side_revolute parent="${name}_shoulder_pan_servo_link" name="${name}_shoulder_pan" llimit="-1.57" ulimit="1.57" vlimit="0.524" color="Black">
      <origin xyz="0 0 0.0205" rpy="0 -1.57 0"/>
    </rx28_side_revolute>

    <!-- Shoulder lift -->
    <dynamixel_rx28_tilt parent="${name}_shoulder_pan_link" name="${name}_shoulder_lift_servo" color="Black">
      <origin xyz="${0.0513-0.013+0.0035} 0 0" rpy="0 0 0"/>
    </dynamixel_rx28_tilt>
    <rx28_hinge parent="${name}_shoulder_lift_servo_link" name="${name}_shoulder_lift" llimit="-0.2" ulimit="2.617" vlimit="0.524" color="Black">
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </rx28_hinge>
    <standoffs parent="${name}_shoulder_lift_link" name="${name}_shoulder_standoff" length="0.0762" >
      <origin xyz="0.03 0 0.0" rpy="0 0 0"/>
    </standoffs>

    <!-- Elbow -->
    <rx28_side_fixed parent="${name}_shoulder_standoff_link" name="${name}_elbow_flex_fixed" color="Black">
      <origin xyz="0.0762 0 0" rpy="0 0 0"/>
    </rx28_side_fixed>
    <dynamixel_rx28_tilt parent="${name}_elbow_flex_fixed_link" name="${name}_elbow_flex_servo" color="Black">
      <origin xyz="${0.0513-0.013+0.0045} 0 0" rpy="0 0 0"/>
    </dynamixel_rx28_tilt>
    <rx28_hinge parent="${name}_elbow_flex_servo_link" name="${name}_elbow_flex" llimit="-1.57" ulimit="2.617" vlimit="0.524" color="Black">
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </rx28_hinge>
    <standoffs parent="${name}_elbow_flex_link" name="${name}_elbow_standoff" length="0.0762" >
      <origin xyz="0.03 0 0.0" rpy="0 0 0"/>
    </standoffs>

    <!-- Wrist flex -->
    <ax12_side_fixed parent="${name}_elbow_standoff_link" name="${name}_wrist_flex_fixed" color="Black">
      <origin xyz="0.0762 0 0" rpy="0 -1.57 0"/>
    </ax12_side_fixed>
    <dynamixel_ax12_tilt parent="${name}_wrist_flex_fixed_link" name="${name}_wrist_flex_servo" color="Black">
      <origin xyz="0 0 ${-0.0513+0.013-0.0045}" rpy="0 -3.14 0"/>
    </dynamixel_ax12_tilt>
    <ax12_hinge_revolute parent="${name}_wrist_flex_servo_link" name="${name}_wrist_flex" llimit="-1.57" ulimit="1.57" vlimit="0.785" color="Black">
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </ax12_hinge_revolute>

    <!-- Wrist roll -->
    <joint name="${name}_wrist_roll_joint" type="revolute">
      <axis xyz="1 0 0" />
      <limit effort="30" velocity="0.785" lower="-2.617" upper="2.617"/>
      <origin xyz="0 0 0.028" rpy="0 -1.57 0" />
      <parent link="${name}_wrist_flex_link"/>
      <child link="${name}_wrist_roll_link"/>
    </joint>
    <link name="${name}_wrist_roll_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>
      <visual>
        <origin xyz="${0.0381/2} 0 0" rpy="0 0 1.57" />
        <geometry>
          <mesh filename="package://maxwell_defs/meshes/ax12.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="${0.040/2} 0.0 ${-(0.0506-0.024)/2} " rpy="0 0 0" />
        <geometry>
          <box size="0.040 0.032 0.0501"/>
        </geometry>
      </collision>
    </link>

  </macro>

</robot>
